version: '3.8'

services:

  nginx:
    container_name: ds-app-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '18080:80'
    volumes:
      - ./app:/app/
    links:
      - php

  php:
    container_name: ds-app-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./app:/app/