version: '3'

services:

  nginx:
    container_name: symfony-component-di-gc-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '18080:80'
    volumes:
      - ./src:/app/
    links:
      - php

  php:
    container_name: symfony-component-di-gc-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ./src:/app/