parameters:
  string_generator_collection_count: 30
  string_generator_length: 20

services:
  _defaults:
    autowire: true
    autoconfigure: true

  default_string_rot13_converter:
    class: DS\Data\Converters\StringRot13Converter

  default_alpha_to_number_converter:
    class: DS\Data\Converters\AlphaToNumberConverter

  string_generator:
    class: DS\Data\Generators\StringGenerator
    arguments:
      $length: '%string_generator_length%'

  string_collection_generator:
    class: DS\Data\Generators\AnyCollectionGenerator
    arguments:
      $valueGenerator: '@string_generator'
      $count: '%string_generator_collection_count%'

  random_converters_ranges:
    class: DS\Data\Ranges\ArrayRange
    arguments:
      $items:
        - '@default_string_rot13_converter'
        - '@default_alpha_to_number_converter'

  random_converters:
    class: DS\Data\Generators\AnyGenerator
    arguments:
      $ranges:
        - '@random_converters_ranges'